app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

products_page:
  path: /products
  defaults: { _controller: AppBundle:Products:index }


products_add:
  path: /products/add
  defaults: { _controller: AppBundle:Products:add }

admin_page:
  path: /admin
  defaults: { _controller: AppBundle:Admin:index }
